use_frameworks!

platform :ios, '9.0'

target 'FTPopTransitionModule_Example' do
  pod 'FTPopTransitionModule', :path => '../'

  target 'FTPopTransitionModule_Tests' do
    inherit! :search_paths

    
  end
end
